// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.29;

import {EnumerableSetLib} from "solady/utils/EnumerableSetLib.sol";
import {Key, KeyLib} from "../../src/libraries/KeyLib.sol";
import {TestKey, TestKeyManager} from "./TestKeyManager.sol";
import {Call} from "../../src/libraries/CallLib.sol";
import {Settings, SettingsLib} from "../../src/libraries/SettingsLib.sol";

/// Callbacks for calls generated by the invariant handler
/// they are triggered sequentially in order of Call[] after each call to execute
interface IHandlerGhostCallbacks {
    function ghost_RegisterCallback(Key memory key) external;
    function ghost_RevokeCallback(bytes32 keyHash) external;
    function ghost_UpdateCallback(bytes32 keyHash, Settings settings) external;
    function ghost_ExecuteCallback(Call[] memory calls) external;
}

/// Base contract for mirroring the state of signerAccount
abstract contract GhostStateTracker {
    using KeyLib for Key;
    using TestKeyManager for TestKey;
    using EnumerableSetLib for EnumerableSetLib.Bytes32Set;

    EnumerableSetLib.Bytes32Set internal _lastKnownKeyHashes;

    /// @notice Ghost callback to track registered keys
    function ghost_RegisterCallback(Key memory key) external {
        bytes32 keyHash = key.hash();
        _lastKnownKeyHashes.add(keyHash);
    }

    function ghost_RevokeCallback(bytes32 keyHash) external {
        _lastKnownKeyHashes.remove(keyHash);
    }

    // Noop
    function ghost_UpdateCallback(bytes32 keyHash, Settings settings) external {}

    function ghost_ExecuteCallback(Call[] memory calls) external {}
}
